#!/bin/bash

#a spinner displaying WAIT, just for the design

spinner()
{
pid=$$
spin[0]="W"
spin[1]="A"
spin[2]="I"
spin[3]="T"
spin[4]=" "
  	mpg123 music.mp3 &> /dev/null &
echo -ne "Please wait ... This may take some time ! ${spin[4]}"

while kill -0 $pid 2> /dev/null;
do
  for i in "${spin[@]}"
  do
        echo -ne "\b$i"
        sleep 0.2
  done
done
}

#main function

caseONE()
{
spinner &
dossier=$(pwd)
firstthingsFirst &> /dev/null
mpg123 $(pwd)/music.mp3 &> /dev/null &
dlHosts &> /dev/null
makeitBeautiful
cat $(pwd)/unique >> $(pwd)/hosts
cp /etc/hosts /etc/.hosts_backup
cp $(pwd)/hosts /etc/hosts
shreditBeautiful
apt -y autoremove mpg123 &> /dev/null
unset dossier
unset hostname
unset username
shred -f -n0 -z -u $(pwd)/hosts
clear
echo "You are safe now... Almost !"
sleep 3
}

#here you can find all the lists downloaded

dlHosts()
{
wget https://block.energized.pro/unified/formats/domains.txt -O $(pwd)/energized
wget https://mkb2091.github.io/blockconvert/output/domains.txt -O $(pwd)/blockconvert
wget https://dbl.oisd.nl/ -O $(pwd)/oisd
wget https://raw.githubusercontent.com/columndeeply/hosts/main/hosts00 -O $(pwd)/pow
}

#merges and organizes the host file, adds some p0rn websites not added to the downloaded lists
#IF IT'S NOT ENOUGH YOU CAN ADD YOUR OWN WEBSITES TO BLOCK WHEN RUNNING THE SCRIPT
#adds duckduckgo to the whitelist, because aggressive hosts lists surprisingly block it

makeitBeautiful()
{
sed '/^#/d' $(pwd)/energized > $(pwd)/cleanenergized
sed '/^#/d' $(pwd)/blockconvert > $(pwd)/cleanblockconvert
sed '/^#/d' $(pwd)/oisd > $(pwd)/cleanoisd
sed -i -e 's/127.0.0.1 /0.0.0.0       /g' $(pwd)/pow
cat $(pwd)/cleanenergized >> $(pwd)/cleanblockconvert
cat $(pwd)/cleanblockconvert >> $(pwd)/cleanoisd
echo "hdporn92.com
www.hdporn92.com
iceporncasting.com
iceporncasting.net
www.iceporncasting.com
www.iceporncasting.net" >> $(pwd)/cleanoisd
awk '{print "0.0.0.0       "$0}' $(pwd)/cleanoisd > $(pwd)/readyoisd
cat $(pwd)/readyoisd >> $(pwd)/pow
sed -i '/duckduckgo.com/d' $(pwd)/pow
sort $(pwd)/pow | uniq -u > $(pwd)/unique
}

#shreds and deletes all files unecessary

shreditBeautiful()
{
shred -f -n0 -z -u $(pwd)/energized
shred -f -n0 -z -u $(pwd)/cleanenergized
shred -f -n0 -z -u $(pwd)/blockconvert
shred -f -n0 -z -u $(pwd)/cleanblockconvert
shred -f -n0 -z -u $(pwd)/oisd
shred -f -n0 -z -u $(pwd)/cleanoisd
shred -f -n0 -z -u $(pwd)/pow
shred -f -n0 -z -u $(pwd)/readyoisd
shred -f -n0 -z -u $(pwd)/unique
shred -f -n0 -z -u $(pwd)/music.mp3
}

#Downloads the chiptune music, installs the player, resets the /etc/hosts file to what it should be in case it would had been modified previously

firstthingsFirst()
{
hostname=$(cat /etc/hostname)
wget musicjapan.free.fr/music.mp3 -O $(pwd)/music.mp3
apt -y install mpg123

echo "#############################################
#                                           #
#  =====                    =   =           #
#  =    =                   =   =           #
#  =    =                   =====           #
#  =====  O M I T I E N     =   = O S T S   #
#                                           #
#  No Porn. No Bullshit. Extreme !          #
#                                           #
#############################################

127.0.0.1	localhost
127.0.1.1	$hostname

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters" > hosts
}

#title screen function

titleOP()
{
clear
sitesblocked=$(wc -l < /etc/hosts)
username=$(awk -F ':' '{ print $1}' /etc/passwd | tail -n 1)
echo -e "#############################################
#                                           #
#  =====                    =   =           #
#  =    =                   =   =           #
#  =    =                   =====           #
#  =====  O M I T I E N     =   = O S T S   #
#                                           #
#  No Porn. No Bullshit. Extreme !          #
#                                           #
#############################################

Hello ${username^} !
Your hosts file is currently blocking ${sitesblocked-20} websites.
What would you like to do today ?
[choose a number]

1) Set the Domitien Hosts file
2) Backup the hosts file to previous state
3) Add a website
4) Remove a website
5) Exit \n "

read choice
case $choice in
1)
caseONE
clear
exit ;;
2)
cp /etc/.hosts_backup /etc/hosts
echo "Backup complete."
sleep 3
clear 
exit ;;
3)
echo -e "Please enter the website you wish to add \n (example : example.com / no www, no https, so spaces) \n "
read website
echo "0.0.0.0       www.$website" >> /etc/hosts
echo "0.0.0.0       $website" >> /etc/hosts
sort /etc/hosts | uniq -u > /etc/hoststemp
cp /etc/hoststemp /etc/hosts
shred -f -n0 -z -u /etc/hoststemp
echo "Successfully added to list."
sleep 3
clear
exit ;;
4)
echo -e "Please enter the website you wish to remove from list \n (example : duckduckgo.com) \n"
read website
sed -i "/$website/d" /etc/hosts
echo "Successfully removed from list."
sleep 3
clear
exit ;;
5) echo "See you soon."
sleep 3
clear
exit ;;
*) echo "Wrong option, please start the script again." 
sleep 3
clear
exit ;;
esac
}

#starts the title screen
titleOP
